.TH "globals.cpp" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globals.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'globals\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMHR::hrResult\fP \fBhrGlobalResult\fP"
.br
.ti -1c
.RI "\fBMHR::hrResult\fP \fBhrOldGlobalResult\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBMHR::hrResult\fP hrGlobalResult"

.PP
Definition at line 11 of file globals\&.cpp\&.
.SS "\fBMHR::hrResult\fP hrOldGlobalResult"

.PP
Definition at line 12 of file globals\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
