.TH "algorithms/Eulerian/ideal_bandpassing.cpp" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithms/Eulerian/ideal_bandpassing.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ideal_bandpassing\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMHR::ideal_bandpassing\fP (const vector< Mat > &src, vector< Mat > &dst, double wl, double wh, double samplingRate)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
