.TH "MBProgressHUD()" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MBProgressHUD() \- 
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) - \fBsetupLabels\fP"
.br
.ti -1c
.RI "(void) - \fBregisterForKVO\fP"
.br
.ti -1c
.RI "(void) - \fBunregisterFromKVO\fP"
.br
.ti -1c
.RI "(NSArray *) - \fBobservableKeypaths\fP"
.br
.ti -1c
.RI "(void) - \fBregisterForNotifications\fP"
.br
.ti -1c
.RI "(void) - \fBunregisterFromNotifications\fP"
.br
.ti -1c
.RI "(void) - \fBupdateUIForKeypath:\fP"
.br
.ti -1c
.RI "(void) - \fBhideUsingAnimation:\fP"
.br
.ti -1c
.RI "(void) - \fBshowUsingAnimation:\fP"
.br
.ti -1c
.RI "(void) - \fBdone\fP"
.br
.ti -1c
.RI "(void) - \fBupdateIndicators\fP"
.br
.ti -1c
.RI "(void) - \fBhandleGraceTimer:\fP"
.br
.ti -1c
.RI "(void) - \fBhandleMinShowTimer:\fP"
.br
.ti -1c
.RI "(void) - \fBsetTransformForCurrentOrientation:\fP"
.br
.ti -1c
.RI "(void) - \fBcleanUp\fP"
.br
.ti -1c
.RI "(void) - \fBlaunchExecution\fP"
.br
.ti -1c
.RI "(void) - \fBdeviceOrientationDidChange:\fP"
.br
.ti -1c
.RI "(void) - \fBhideDelayed:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UIView * \fBindicator\fP"
.br
.ti -1c
.RI "NSTimer * \fBgraceTimer\fP"
.br
.ti -1c
.RI "NSTimer * \fBminShowTimer\fP"
.br
.ti -1c
.RI "NSDate * \fBshowStarted\fP"
.br
.ti -1c
.RI "CGSize \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file MBProgressHUD\&.m\&.
.SH "Method Documentation"
.PP 
.SS "- (void) cleanUp "

.SS "- (void) deviceOrientationDidChange: (NSNotification *)notification"

.SS "- (void) done "

.SS "- (void) handleGraceTimer: (NSTimer *)theTimer"

.SS "- (void) handleMinShowTimer: (NSTimer *)theTimer"

.SS "- (void) hideDelayed: (NSNumber *)animated"

.SS "- (void) hideUsingAnimation: (BOOL)animated"

.SS "- (void) launchExecution "

.SS "- (NSArray *) observableKeypaths "

.SS "- (void) registerForKVO "

.SS "- (void) registerForNotifications "

.SS "- (void) setTransformForCurrentOrientation: (BOOL)animated"

.SS "- (void) setupLabels "

.SS "- (void) showUsingAnimation: (BOOL)animated"

.SS "- (void) unregisterFromKVO "

.SS "- (void) unregisterFromNotifications "

.SS "- (void) updateIndicators "

.SS "- (void) updateUIForKeypath: (NSString *)keyPath"

.SH "Property Documentation"
.PP 
.SS "- (NSTimer*) graceTimer\fC [read]\fP, \fC [write]\fP, \fC [atomic]\fP, \fC [assign]\fP"

.PP
Definition at line 71 of file MBProgressHUD\&.m\&.
.SS "- (UIView*) indicator\fC [read]\fP, \fC [write]\fP, \fC [atomic]\fP, \fC [assign]\fP"

.PP
Definition at line 70 of file MBProgressHUD\&.m\&.
.SS "- (NSTimer*) minShowTimer\fC [read]\fP, \fC [write]\fP, \fC [atomic]\fP, \fC [assign]\fP"

.PP
Definition at line 72 of file MBProgressHUD\&.m\&.
.SS "- (NSDate*) showStarted\fC [read]\fP, \fC [write]\fP, \fC [atomic]\fP, \fC [assign]\fP"

.PP
Definition at line 73 of file MBProgressHUD\&.m\&.
.SS "- (CGSize) size\fC [read]\fP, \fC [write]\fP, \fC [atomic]\fP, \fC [assign]\fP"

.PP
Definition at line 74 of file MBProgressHUD\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
