.TH "MainView/MHRMainViewController.hpp" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainView/MHRMainViewController.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br
\fC#import <opencv2/core/core\&.hpp>\fP
.br
\fC#import <opencv2/imgproc/types_c\&.h>\fP
.br
\fC#import <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#import <opencv2/highgui/ios\&.h>\fP
.br
\fC#import <opencv2/highgui/cap_ios\&.h>\fP
.br
\fC#import <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#import <opencv2/highgui/highgui_c\&.h>\fP
.br
\fC#import <time\&.h>\fP
.br
\fC#import 'UIView+Position\&.h'\fP
.br
\fC#import 'MBProgressHUD\&.h'\fP
.br
\fC#import 'MHRUtilities\&.h'\fP
.br
\fC#import 'MHRResultViewController\&.hpp'\fP
.br
\fC#import 'MHRSettingsViewController\&.h'\fP
.br
\fC#import 'auto_start\&.hpp'\fP
.br
\fC#import 'globals\&.h'\fP
.br
\fC#import 'processingCumulative\&.h'\fP
.br
\fC#import 'processingPerBlock\&.h'\fP
.br
\fC#import 'matlab\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMHRMainViewController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
