.TH "ResultView/MHRResultViewController.hpp" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResultView/MHRResultViewController.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br
\fC#import 'UIAlertView+Block\&.h'\fP
.br
\fC#import 'config\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMHRResultViewController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
