.TH "MHRSettingsViewController" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MHRSettingsViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MHRSettingsViewController\&.h>\fP
.PP
Inherits UIViewController\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "id< \fBMHRSettingsViewDelegate\fP > \fB_delegate\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "id \fBdelegate\fP"
.br
.ti -1c
.RI "BOOL \fBdebugModeOn\fP"
.br
.ti -1c
.RI "BOOL \fBthreeChanModeOn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file MHRSettingsViewController\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "- (id<\fBMHRSettingsViewDelegate\fP>) _delegate\fC [protected]\fP"

.PP
Definition at line 22 of file MHRSettingsViewController\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (BOOL) debugModeOn\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 27 of file MHRSettingsViewController\&.h\&.
.SS "- (id) delegate\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 25 of file MHRSettingsViewController\&.h\&.
.SS "- (BOOL) threeChanModeOn\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 28 of file MHRSettingsViewController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
