.TH "SettingsView/MHRSettingsViewController.m" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SettingsView/MHRSettingsViewController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'MHRSettingsViewController\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
