.TH "MHRUtilities" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MHRUtilities \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MHRUtilities\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(UIColor *) - \fBMFUIColorMakeFromRGBArray\fP"
.br
.ti -1c
.RI "(UIColor *) - \fBMFUIColorMakeFromRGBAArray\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(NSString *) + \fBreport_memory\fP"
.br
.ti -1c
.RI "(void) + \fBcreateDirectory:\fP"
.br
.ti -1c
.RI "(void) + \fBsetTorchModeOn:\fP"
.br
.ti -1c
.RI "(CALayer *) + \fBnewRectangleLayer:pListKey:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file MHRUtilities\&.h\&.
.SH "Method Documentation"
.PP 
.SS "+ (void) createDirectory: (NSString *)directoryPath"

.PP
Definition at line 37 of file MHRUtilities\&.m\&.
.SS "- (UIColor *) MFUIColorMakeFromRGBAArray (NSArray *)rgbaArray"

.PP
Definition at line 79 of file MHRUtilities\&.m\&.
.SS "- (UIColor *) MFUIColorMakeFromRGBArray (NSArray *)rgbArray"

.PP
Definition at line 70 of file MHRUtilities\&.m\&.
.SS "+ (CALayer *) newRectangleLayer: (CGRect)frame(NSString *)pListKey"

.PP
Definition at line 89 of file MHRUtilities\&.m\&.
.SS "+ (NSString *) report_memory "

.PP
Definition at line 16 of file MHRUtilities\&.m\&.
.SS "+ (void) setTorchModeOn: (BOOL)isOn"

.PP
Definition at line 50 of file MHRUtilities\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
