.TH "algorithms/processingCumulative.cpp" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithms/processingCumulative.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'processingCumulative\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMHR::processingCumulative\fP (vector< double > &temporal_mean, vector< double > temp, hrResult &currentResult)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
