.TH "UIAlertView(Block)" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIAlertView(Block) \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 18 of file UIAlertView+Block\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
