.TH "MisfitHeartRate/algorithms/math Directory Reference" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/math Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmatlab\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmatlab\&.h\fP"
.br
.in -1c
