.TH "MisfitHeartRate Directory Reference" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBalgorithms\fP"
.br
.ti -1c
.RI "directory \fBMainView\fP"
.br
.ti -1c
.RI "directory \fBResultView\fP"
.br
.ti -1c
.RI "directory \fBSettingsView\fP"
.br
.ti -1c
.RI "directory \fBUtilities\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBglobals\&.cpp\fP"
.br
.ti -1c
.RI "file \fBglobals\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.m\fP"
.br
.ti -1c
.RI "file \fBMHRAppDelegate\&.hpp\fP"
.br
.ti -1c
.RI "file \fBMHRAppDelegate\&.mm\fP"
.br
.in -1c
