.TH "algorithms Directory Reference" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithms Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEulerian\fP"
.br
.ti -1c
.RI "directory \fBfiles\fP"
.br
.ti -1c
.RI "directory \fBHeartRateCal\fP"
.br
.ti -1c
.RI "directory \fBimage\fP"
.br
.ti -1c
.RI "directory \fBmath\fP"
.br
.ti -1c
.RI "directory \fBmatrix\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBface_params\&.h\fP"
.br
.ti -1c
.RI "file \fBfinger_params\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessingCumulative\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprocessingCumulative\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessingPerBlock\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprocessingPerBlock\&.h\fP"
.br
.in -1c
