.TH "MisfitHeartRate/algorithms/Eulerian Directory Reference" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/Eulerian Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbuild_Gdown_stack\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbuild_Gdown_stack\&.h\fP"
.br
.ti -1c
.RI "file \fBeulerian\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeulerian\&.h\fP"
.br
.ti -1c
.RI "file \fBideal_bandpassing\&.cpp\fP"
.br
.ti -1c
.RI "file \fBideal_bandpassing\&.h\fP"
.br
.in -1c
