.TH "MisfitHeartRate/Utilities/auto_start.hpp" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/Utilities/auto_start.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'opencv2/objdetect/objdetect\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#import 'MHRMainViewController\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
