.TH "MisfitHeartRate/Utilities/BlockAdditions.h" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/Utilities/BlockAdditions.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBkPhotoActionSheetTag\fP   10000"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(^ \fBVoidBlock\fP )()"
.br
.ti -1c
.RI "typedef void(^ \fBDismissBlock\fP )(int buttonIndex)"
.br
.ti -1c
.RI "typedef void(^ \fBCancelBlock\fP )()"
.br
.ti -1c
.RI "typedef void(^ \fBPhotoPickedBlock\fP )(UIImage *chosenImage)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define kPhotoActionSheetTag   10000"

.PP
Definition at line 18 of file BlockAdditions\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef void(^ CancelBlock)()"

.PP
Definition at line 15 of file BlockAdditions\&.h\&.
.SS "typedef void(^ DismissBlock)(int buttonIndex)"

.PP
Definition at line 14 of file BlockAdditions\&.h\&.
.SS "typedef void(^ PhotoPickedBlock)(UIImage *chosenImage)"

.PP
Definition at line 16 of file BlockAdditions\&.h\&.
.SS "typedef void(^ VoidBlock)()"

.PP
Definition at line 12 of file BlockAdditions\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
