.TH "algorithms/Eulerian/build_Gdown_stack.h" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithms/Eulerian/build_Gdown_stack.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'files\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMHR::build_Gdown_Stack\fP (const vector< Mat > &vid, vector< Mat > &GDownStack, int startIndex, int endIndex, int level)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
