.TH "MisfitHeartRate/algorithms/config.cpp" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/config.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMHR::setFaceParams\fP ()"
.br
.ti -1c
.RI "void \fBMHR::setFingerParams\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBMHR::_DEBUG_MODE\fP = 0"
.br
.ti -1c
.RI "int \fBMHR::_THREE_CHAN_MODE\fP = 0"
.br
.ti -1c
.RI "bool \fBMHR::_FACE_MODE\fP = true"
.br
.ti -1c
.RI "String \fBMHR::_outputPath\fP = 'NULL'"
.br
.ti -1c
.RI "double \fBMHR::_eulerian_alpha\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_eulerian_pyrLevel\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_eulerian_minHR\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_eulerian_maxHR\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_eulerian_frameRate\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_eulerian_chromaMagnifier\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_frameRate\fP = 30"
.br
.ti -1c
.RI "int \fBMHR::_number_of_channels\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_Gpyr_filter_length\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_startFrame\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_endFrame\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_window_size_in_sec\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_overlap_ratio\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_max_bpm\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_cutoff_freq\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_time_lag\fP = -1"
.br
.ti -1c
.RI "String \fBMHR::_colourspace\fP = '-1'"
.br
.ti -1c
.RI "int \fBMHR::_channels_to_process\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_number_of_bins_heartRate\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_flagDebug\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_flagGetRaw\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_startIndex\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_endIndex\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_peakStrengthThreshold_fraction\fP = -1"
.br
.ti -1c
.RI "String \fBMHR::_frames2signalConversionMethod\fP = '-1'"
.br
.ti -1c
.RI "int \fBMHR::_frame_downsampling_filt_rows\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_frame_downsampling_filt_cols\fP = -1"
.br
.ti -1c
.RI "Mat \fBMHR::_frame_downsampling_filt\fP"
.br
.ti -1c
.RI "int \fBMHR::_trimmed_size\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_training_time_start\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_training_time_end\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_number_of_bins\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_pct_reach_below_mode\fP = -1"
.br
.ti -1c
.RI "double \fBMHR::_pct_reach_above_mode\fP = -1"
.br
.ti -1c
.RI "int \fBMHR::_beatSignalFilterKernel_size\fP = -1"
.br
.ti -1c
.RI "Mat \fBMHR::_beatSignalFilterKernel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
