.TH "MisfitHeartRate/algorithms/config.h" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/config.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'face_params\&.h'\fP
.br
\fC#include 'finger_params\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMHR::setFaceParams\fP ()"
.br
.ti -1c
.RI "void \fBMHR::setFingerParams\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBMHR::NaN\fP = -1e9"
.br
.ti -1c
.RI "const int \fBMHR::_framesBlock_size\fP = 128"
.br
.ti -1c
.RI "const int \fBMHR::_minVidLength\fP = 15"
.br
.ti -1c
.RI "const int \fBMHR::_maxVidLength\fP = 30"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
