.TH "MisfitHeartRate/algorithms/Eulerian/eulerian.cpp" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/Eulerian/eulerian.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'eulerian\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMHR::eulerianGaussianPyramidMagnification\fP (const vector< Mat > &vid, vector< Mat > &ans, String outDir, double alpha, int level, double freqBandLowEnd, double freqBandHighEnd, double samplingRate, double chromAttenuation)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
