.TH "MisfitHeartRate/algorithms/finger_params.h" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/finger_params.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <opencv2/core/core\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/types_c\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBMHR::_finger_eulerian_alpha\fP = 50"
.br
.ti -1c
.RI "const double \fBMHR::_finger_eulerian_pyrLevel\fP = 6"
.br
.ti -1c
.RI "const double \fBMHR::_finger_eulerian_minHR\fP = 30"
.br
.ti -1c
.RI "const double \fBMHR::_finger_eulerian_maxHR\fP = 240"
.br
.ti -1c
.RI "const double \fBMHR::_finger_eulerian_frameRate\fP = 30"
.br
.ti -1c
.RI "const double \fBMHR::_finger_eulerian_chromaMagnifier\fP = 1"
.br
.ti -1c
.RI "const int \fBMHR::_finger_number_of_channels\fP = 3"
.br
.ti -1c
.RI "const int \fBMHR::_finger_Gpyr_filter_length\fP = 5"
.br
.ti -1c
.RI "const int \fBMHR::_finger_startFrame\fP = 0"
.br
.ti -1c
.RI "const int \fBMHR::_finger_endFrame\fP = 0"
.br
.ti -1c
.RI "const double \fBMHR::_finger_window_size_in_sec\fP = 10"
.br
.ti -1c
.RI "const double \fBMHR::_finger_overlap_ratio\fP = 0"
.br
.ti -1c
.RI "const double \fBMHR::_finger_max_bpm\fP = 200"
.br
.ti -1c
.RI "const double \fBMHR::_finger_cutoff_freq\fP = 2\&.5"
.br
.ti -1c
.RI "const double \fBMHR::_finger_time_lag\fP = 3"
.br
.ti -1c
.RI "const String \fBMHR::_finger_colourspace\fP = 'rgb'"
.br
.ti -1c
.RI "const int \fBMHR::_finger_channels_to_process\fP = 0"
.br
.ti -1c
.RI "const int \fBMHR::_finger_number_of_bins_heartRate\fP = 5"
.br
.ti -1c
.RI "const int \fBMHR::_finger_flagDebug\fP = 0"
.br
.ti -1c
.RI "const int \fBMHR::_finger_flagGetRaw\fP = 0"
.br
.ti -1c
.RI "const int \fBMHR::_finger_startIndex\fP = 1"
.br
.ti -1c
.RI "const int \fBMHR::_finger_endIndex\fP = 0"
.br
.ti -1c
.RI "const double \fBMHR::_finger_peakStrengthThreshold_fraction\fP = 0"
.br
.ti -1c
.RI "const String \fBMHR::_finger_frames2signalConversionMethod\fP = 'mode-balance'"
.br
.ti -1c
.RI "const int \fBMHR::_finger_frame_downsampling_filt_rows\fP = 7"
.br
.ti -1c
.RI "const int \fBMHR::_finger_frame_downsampling_filt_cols\fP = 7"
.br
.ti -1c
.RI "const Mat \fBMHR::_finger_frame_downsampling_filt\fP"
.br
.ti -1c
.RI "const int \fBMHR::_finger_trimmed_size\fP = 30"
.br
.ti -1c
.RI "const double \fBMHR::_finger_training_time_start\fP = 0"
.br
.ti -1c
.RI "const double \fBMHR::_finger_training_time_end\fP = 0\&.2"
.br
.ti -1c
.RI "const int \fBMHR::_finger_number_of_bins\fP = 50"
.br
.ti -1c
.RI "const double \fBMHR::_finger_pct_reach_below_mode\fP = 45"
.br
.ti -1c
.RI "const double \fBMHR::_finger_pct_reach_above_mode\fP = 45"
.br
.ti -1c
.RI "const int \fBMHR::_finger_beatSignalFilterKernel_size\fP = 15"
.br
.ti -1c
.RI "const Mat \fBMHR::_finger_beatSignalFilterKernel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
