.TH "MisfitHeartRate/algorithms/HeartRateCal/frames2signal.h" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/HeartRateCal/frames2signal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'matlab\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "vector< double > \fBMHR::frames2signal\fP (const vector< Mat > &monoframes, const String &conversion_method, double fr, double cutoff_freq, double &lower_range, double &upper_range, bool isCalcMode)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
