.TH "MisfitHeartRate/algorithms/HeartRateCal/hb_counter_pda.h" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/HeartRateCal/hb_counter_pda.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'image\&.h'\fP
.br
\fC#include 'matlab\&.h'\fP
.br
\fC#include 'hr_structures\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "vector< int > \fBMHR::hb_counter_pda\fP (vector< double > temporal_mean, double fr, int firstSample, int window_size, double overlap_ratio, double minPeakDistance, double threshold, hrDebug &debug)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
