.TH "MisfitHeartRate/algorithms/HeartRateCal/hr_calculator.h" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/HeartRateCal/hr_calculator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'matlab\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMHR::hr_calculator\fP (const vector< int > &heartBeatPositions, double frameRate, vector< double > &ans)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
