.TH "MisfitHeartRate/algorithms/HeartRateCal/hr_signal_calc.h" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/HeartRateCal/hr_signal_calc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'hb_counter_pda\&.h'\fP
.br
\fC#include 'hb_counter_autocorr\&.h'\fP
.br
\fC#include 'hr_calculator\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "hrResult \fBMHR::hr_signal_calc\fP (vector< double > &temporal_mean, int firstSample, int window_size, double frameRate, double overlap_ratio, double max_bpm, double threshold_fraction)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
