.TH "algorithms/matrix/matrix.cpp" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithms/matrix/matrix.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'matrix\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Mat \fBMHR::atan2Mat\fP (const Mat &a, const Mat &b)"
.br
.ti -1c
.RI "Mat \fBMHR::powMat\fP (const Mat &src, double n)"
.br
.ti -1c
.RI "Mat \fBMHR::add\fP (const Mat &a, const Mat &b)"
.br
.ti -1c
.RI "Mat \fBMHR::multiply\fP (const Mat &a, const Mat &b)"
.br
.ti -1c
.RI "Mat \fBMHR::multiply\fP (const Mat &a, double x)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
