.TH "MBBarProgressView" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MBBarProgressView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MBProgressHUD\&.h>\fP
.PP
Inherits UIView\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBprogress\fP"
.br
.ti -1c
.RI "UIColor * \fBlineColor\fP"
.br
.ti -1c
.RI "UIColor * \fBprogressRemainingColor\fP"
.br
.ti -1c
.RI "UIColor * \fBprogressColor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A flat bar progress view\&. 
.PP
Definition at line 475 of file MBProgressHUD\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (UIColor*) lineColor\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
Bar border line color\&. Defaults to white [UIColor whiteColor]\&. 
.PP
Definition at line 486 of file MBProgressHUD\&.h\&.
.SS "- (float) progress\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
Progress (0\&.0 to 1\&.0) 
.PP
Definition at line 480 of file MBProgressHUD\&.h\&.
.SS "- (UIColor*) progressColor\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
Bar progress color\&. Defaults to white [UIColor whiteColor]\&. 
.PP
Definition at line 498 of file MBProgressHUD\&.h\&.
.SS "- (UIColor*) progressRemainingColor\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
Bar background color\&. Defaults to clear [UIColor clearColor]; 
.PP
Definition at line 492 of file MBProgressHUD\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
