.TH "<MBProgressHUDDelegate>" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<MBProgressHUDDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MBProgressHUD\&.h>\fP
.PP
Inherits <UIViewNSObject>\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) - \fBhudWasHidden:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 430 of file MBProgressHUD\&.h\&.
.SH "Method Documentation"
.PP 
.SS "- (void) hudWasHidden: (\fBMBProgressHUD\fP *)hud\fC [optional]\fP"
Called after the HUD was fully hidden from the screen\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
