.TH "MBRoundProgressView" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MBRoundProgressView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MBProgressHUD\&.h>\fP
.PP
Inherits UIView\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBprogress\fP"
.br
.ti -1c
.RI "UIColor * \fBprogressTintColor\fP"
.br
.ti -1c
.RI "UIColor * \fBbackgroundTintColor\fP"
.br
.ti -1c
.RI "BOOL \fBannular\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A progress view for showing definite progress by filling up a circle (pie chart)\&. 
.PP
Definition at line 445 of file MBProgressHUD\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (BOOL) annular\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 467 of file MBProgressHUD\&.h\&.
.SS "- (UIColor*) backgroundTintColor\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
Indicator background (non-progress) color\&. Defaults to translucent white (alpha 0\&.1) 
.PP
Definition at line 462 of file MBProgressHUD\&.h\&.
.SS "- (float) progress\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
Progress (0\&.0 to 1\&.0) 
.PP
Definition at line 450 of file MBProgressHUD\&.h\&.
.SS "- (UIColor*) progressTintColor\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
Indicator progress color\&. Defaults to white [UIColor whiteColor] 
.PP
Definition at line 456 of file MBProgressHUD\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
