.TH "MHR::hrDebug" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MHR::hrDebug \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hr_structures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBavg_hr\fP"
.br
.ti -1c
.RI "vector< pair< double, int > > \fBheartBeats\fP"
.br
.ti -1c
.RI "vector< double > \fBheartRates\fP"
.br
.ti -1c
.RI "vector< double > \fBautocorrelation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file hr_structures\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<double> MHR::hrDebug::autocorrelation"

.PP
Definition at line 22 of file hr_structures\&.h\&.
.SS "double MHR::hrDebug::avg_hr"

.PP
Definition at line 19 of file hr_structures\&.h\&.
.SS "vector<pair<double,int> > MHR::hrDebug::heartBeats"

.PP
Definition at line 20 of file hr_structures\&.h\&.
.SS "vector<double> MHR::hrDebug::heartRates"

.PP
Definition at line 21 of file hr_structures\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
