.TH "MHR::hrResult" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MHR::hrResult \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hr_structures\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhrResult\fP ()"
.br
.ti -1c
.RI "\fBhrResult\fP (double \fBautocorr\fP, double \fBpda\fP)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBhrResult\fP &other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBautocorr\fP"
.br
.ti -1c
.RI "double \fBpda\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file hr_structures\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MHR::hrResult::hrResult ()"

.PP
Definition at line 12 of file hr_structures\&.cpp\&.
.SS "MHR::hrResult::hrResult (doubleautocorr, doublepda)"

.PP
Definition at line 13 of file hr_structures\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void MHR::hrResult::operator= (const \fBhrResult\fP &other)"

.PP
Definition at line 20 of file hr_structures\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double MHR::hrResult::autocorr"

.PP
Definition at line 28 of file hr_structures\&.h\&.
.SS "double MHR::hrResult::pda"

.PP
Definition at line 29 of file hr_structures\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
