.TH "MisfitHeartRate/MHRAppDelegate.mm" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/MHRAppDelegate.mm \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'MHRAppDelegate\&.hpp'\fP
.br
\fC#import 'MHRMainViewController\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "NSString *const \fBkSkinPListFileName\fP = @'MisfitHeartRate-Skin'"
.br
.ti -1c
.RI "NSDictionary * \fBpListSkinDict\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "NSString* const kSkinPListFileName = @'MisfitHeartRate-Skin'"

.PP
Definition at line 13 of file MHRAppDelegate\&.mm\&.
.SS "NSDictionary* pListSkinDict"

.PP
Definition at line 22 of file MHRAppDelegate\&.mm\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
