.TH "MisfitHeartRate/MainView/MHRMainViewController.mm" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/MainView/MHRMainViewController.mm \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'MHRMainViewController\&.hpp'\fP
.br
\fC#import 'UIImageCVMatConverter\&.hpp'\fP
.br
\fC#import 'matlab\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBIOS6_Y_DELTA\fP = 60"
.br
.ti -1c
.RI "const int \fBCAMERA_WIDTH\fP = 352"
.br
.ti -1c
.RI "const int \fBCAMERA_HEIGHT\fP = 288"
.br
.ti -1c
.RI "const int \fBIMAGE_WIDTH\fP = 128"
.br
.ti -1c
.RI "const int \fBIMAGE_HEIGHT\fP = 128"
.br
.ti -1c
.RI "const int \fBWIDTH_PADDING\fP = (\fBCAMERA_WIDTH\fP-\fBIMAGE_WIDTH\fP)/2"
.br
.ti -1c
.RI "const int \fBHEIGHT_PADDING\fP = (\fBCAMERA_HEIGHT\fP-\fBIMAGE_HEIGHT\fP)/2"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int CAMERA_HEIGHT = 288"

.PP
Definition at line 15 of file MHRMainViewController\&.mm\&.
.SS "const int CAMERA_WIDTH = 352"

.PP
Definition at line 14 of file MHRMainViewController\&.mm\&.
.SS "const int HEIGHT_PADDING = (\fBCAMERA_HEIGHT\fP-\fBIMAGE_HEIGHT\fP)/2"

.PP
Definition at line 19 of file MHRMainViewController\&.mm\&.
.SS "const int IMAGE_HEIGHT = 128"

.PP
Definition at line 17 of file MHRMainViewController\&.mm\&.
.SS "const int IMAGE_WIDTH = 128"

.PP
Definition at line 16 of file MHRMainViewController\&.mm\&.
.SS "const int IOS6_Y_DELTA = 60"

.PP
Definition at line 13 of file MHRMainViewController\&.mm\&.
.SS "const int WIDTH_PADDING = (\fBCAMERA_WIDTH\fP-\fBIMAGE_WIDTH\fP)/2"

.PP
Definition at line 18 of file MHRMainViewController\&.mm\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
