.TH "MHRMainViewController" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MHRMainViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MHRMainViewController\&.hpp>\fP
.PP
Inherits UIViewController, <CvVideoCameraDelegate>, and \fB<MHRSettingsViewDelegate>\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 33 of file MHRMainViewController\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
