.TH "MHRResultViewController" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MHRResultViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MHRResultViewController\&.hpp>\fP
.PP
Inherits UIViewController\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBautocorrResult\fP"
.br
.ti -1c
.RI "double \fBpdaResult\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file MHRResultViewController\&.hpp\&.
.SH "Property Documentation"
.PP 
.SS "- (double) autocorrResult\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 15 of file MHRResultViewController\&.hpp\&.
.SS "- (double) pdaResult\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 16 of file MHRResultViewController\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
