.TH "algorithms/processingPerBlock.h" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithms/processingPerBlock.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'processingCumulative\&.h'\fP
.br
\fC#include 'eulerian\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMHR::processingPerBlock\fP (const string &srcDir, const string &outDir, int fileStartIndex, int fileEndIndex, bool &isCalcMode, double &lower_range, double &upper_range, hrResult &result, vector< double > &tmp)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
