.TH "MisfitHeartRate/algorithms/run_algorithms.h" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/run_algorithms.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'eulerian\&.h'\fP
.br
\fC#include 'temporal_mean_calc\&.h'\fP
.br
\fC#include 'globals\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "hrResult \fBMHR::run_algorithms\fP (const String &srcDir, const String &outDir, hrResult &currHrResult)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
