.TH "MisfitHeartRate/algorithms/HeartRateCal/temporal_mean_calc.cpp" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/algorithms/HeartRateCal/temporal_mean_calc.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'temporal_mean_calc\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMHR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "vector< double > \fBMHR::temporal_mean_calc\fP (const vector< Mat > &vid, double overlap_ratio, double max_bpm, double cutoff_freq, int colour_channel, String colourspace, double &lower_range, double &upper_range, bool isCalcMode)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
