.TH "UIImageCVMatConverter" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIImageCVMatConverter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <UIImageCVMatConverter\&.hpp>\fP
.PP
Inherits NSObject\&.
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(UIImage *) + \fBUIImageFromCVMat:\fP"
.br
.ti -1c
.RI "(UIImage *) + \fBUIImageFromCVMat:withUIImage:\fP"
.br
.ti -1c
.RI "(cv::Mat) + \fBcvMatFromUIImage:\fP"
.br
.ti -1c
.RI "(cv::Mat) + \fBcvMatGrayFromUIImage:\fP"
.br
.ti -1c
.RI "(UIImage *) + \fBscaleAndRotateImageFrontCamera:\fP"
.br
.ti -1c
.RI "(UIImage *) + \fBscaleAndRotateImageBackCamera:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file UIImageCVMatConverter\&.hpp\&.
.SH "Method Documentation"
.PP 
.SS "+ (Mat) UIImageCVMatConverter: (UIImage *)image"

.PP
Definition at line 84 of file UIImageCVMatConverter\&.mm\&.
.SS "+ (Mat) UIImageCVMatConverter: (UIImage *)image"

.PP
Definition at line 109 of file UIImageCVMatConverter\&.mm\&.
.SS "+ (UIImage *) scaleAndRotateImageBackCamera: (UIImage *)image"

.PP
Definition at line 124 of file UIImageCVMatConverter\&.mm\&.
.SS "+ (UIImage *) scaleAndRotateImageFrontCamera: (UIImage *)image"

.PP
Definition at line 216 of file UIImageCVMatConverter\&.mm\&.
.SS "+ (UIImage *) UIImageFromCVMat: (cv::Mat)cvMat"

.PP
Definition at line 48 of file UIImageCVMatConverter\&.mm\&.
.SS "+ (UIImage *) \fBUIImageFromCVMat:\fP (cv::Mat)cvMat(UIImage*)image"

.PP
Definition at line 16 of file UIImageCVMatConverter\&.mm\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
