.TH "MisfitHeartRate/Utilities/UIImageCVMatConverter.hpp" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/Utilities/UIImageCVMatConverter.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br
\fC#import <opencv2/imgproc/imgproc_c\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUIImageCVMatConverter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
