.TH "Utilities/UIView+Position.h" 3 "Sat Aug 30 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utilities/UIView+Position.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br
\fC#import 'MHRUtilities\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBUIView(Position)\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
