.TH "MisfitHeartRate/Utilities/UIView+Position.m" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MisfitHeartRate/Utilities/UIView+Position.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'UIView+Position\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
