.TH "UIView(Position)" 3 "Fri Aug 22 2014" "Pulsar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIView(Position) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <UIView+Position\&.h>\fP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) - \fBaddCenteredSubview:\fP"
.br
.ti -1c
.RI "(void) - \fBmoveToCenterOfSuperview\fP"
.br
.ti -1c
.RI "(void) - \fBcenterVerticallyInSuperview\fP"
.br
.ti -1c
.RI "(void) - \fBcenterHorizontallyInSuperview\fP"
.br
.ti -1c
.RI "(void) - \fBsetFrameXPlus:yPlus:widthPlus:heightPlus:\fP"
.br
.ti -1c
.RI "(void) - \fBadjustFrameFormiOS6ToiOS7:\fP"
.br
.ti -1c
.RI "(void) - \fBadjustFrameFormiOS7ToiOS6:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "CGPoint \fBframeOrigin\fP"
.br
.ti -1c
.RI "CGSize \fBframeSize\fP"
.br
.ti -1c
.RI "CGFloat \fBframeX\fP"
.br
.ti -1c
.RI "CGFloat \fBframeY\fP"
.br
.ti -1c
.RI "CGFloat \fBframeRight\fP"
.br
.ti -1c
.RI "CGFloat \fBframeBottom\fP"
.br
.ti -1c
.RI "CGFloat \fBframeWidth\fP"
.br
.ti -1c
.RI "CGFloat \fBframeHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file UIView+Position\&.h\&.
.SH "Method Documentation"
.PP 
.SS "- (void) addCenteredSubview: (UIView *)subview"

.PP
Definition at line 84 of file UIView+Position\&.m\&.
.SS "- (void) adjustFrameFormiOS6ToiOS7: (CGFloat)distance"

.PP
Definition at line 111 of file UIView+Position\&.m\&.
.SS "- (void) adjustFrameFormiOS7ToiOS6: (CGFloat)distance"

.PP
Definition at line 119 of file UIView+Position\&.m\&.
.SS "- (void) centerHorizontallyInSuperview "

.PP
Definition at line 100 of file UIView+Position\&.m\&.
.SS "- (void) centerVerticallyInSuperview "

.PP
Definition at line 95 of file UIView+Position\&.m\&.
.SS "- (void) moveToCenterOfSuperview "

.PP
Definition at line 90 of file UIView+Position\&.m\&.
.SS "- (void) setFrameXPlus: (CGFloat)dX(CGFloat)dY(CGFloat)dWidth(CGFloat)dHeight"

.PP
Definition at line 105 of file UIView+Position\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (CGFloat) frameBottom\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 32 of file UIView+Position\&.h\&.
.SS "- (CGFloat) frameHeight\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 35 of file UIView+Position\&.h\&.
.SS "- (CGPoint) frameOrigin\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 24 of file UIView+Position\&.h\&.
.SS "- (CGFloat) frameRight\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 31 of file UIView+Position\&.h\&.
.SS "- (CGSize) frameSize\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 25 of file UIView+Position\&.h\&.
.SS "- (CGFloat) frameWidth\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 34 of file UIView+Position\&.h\&.
.SS "- (CGFloat) frameX\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 27 of file UIView+Position\&.h\&.
.SS "- (CGFloat) frameY\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 28 of file UIView+Position\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pulsar from the source code\&.
